// Generated by Haxe 3.4.7
(function () { "use strict";
var Logic = function(vd) {
	this.vd = vd;
};
Logic.prototype = {
	init: function() {
		var _g = 0;
		while(_g < 30) {
			var i = _g++;
			var tag = new TagItem();
			tag.id = "id" + i;
			tag.name = "tag name" + i;
			tag.count = i;
			this.vd.left.tags.push(tag);
		}
		var _g1 = 0;
		while(_g1 < 36) {
			var i1 = _g1++;
			var img = new ThumbnailImage();
			img.src = "";
			this.vd.thumbnail.images.push(img);
		}
	}
};
var Main = function() { };
Main.main = function() {
	console.log("Hello, world!");
	var vd = new ViewData();
	var vm = new Vue({ el : "#app", data : function() {
		return vd;
	}});
	var logic = new Logic(vd);
	logic.init();
};
var ViewData = function() {
	this.left = new LeftPane();
	this.thumbnail = new Thumbnail();
};
var LeftPane = function() {
	this.tags = [];
};
var TagItem = function() {
};
var Thumbnail = function() {
	this.images = [];
};
var ThumbnailImage = function() {
};
var extype_extern__$ValueOrArray_ValueOrArray_$Impl_$ = {};
extype_extern__$ValueOrArray_ValueOrArray_$Impl_$.toArray = function(this1) {
	if((this1 instanceof Array) && this1.__enum__ == null) {
		return this1;
	} else {
		return [this1];
	}
};
var vuehx__$Vue_PropOptions_$Impl_$ = {};
vuehx__$Vue_PropOptions_$Impl_$._new = function(x) {
	var this1 = x;
	return this1;
};
vuehx__$Vue_PropOptions_$Impl_$.from1 = function(x) {
	x["default"] = x.defaultValue;
	return vuehx__$Vue_PropOptions_$Impl_$._new(x);
};
vuehx__$Vue_PropOptions_$Impl_$.from2 = function(x) {
	x["default"] = x.defaultValue;
	return vuehx__$Vue_PropOptions_$Impl_$._new(x);
};
var vuehx__$Vue_PropType_$Impl_$ = {};
vuehx__$Vue_PropType_$Impl_$.get_String = function() {
	return String;
};
vuehx__$Vue_PropType_$Impl_$.get_Number = function() {
	return Number;
};
vuehx__$Vue_PropType_$Impl_$.get_Boolean = function() {
	return Boolean;
};
vuehx__$Vue_PropType_$Impl_$.get_Function = function() {
	return Function;
};
vuehx__$Vue_PropType_$Impl_$.get_Object = function() {
	return Object;
};
vuehx__$Vue_PropType_$Impl_$.get_Array = function() {
	return Array;
};
vuehx__$Vue_PropType_$Impl_$.get_Symbol = function() {
	return Symbol;
};
var vuehx__$Vue_Component_$Impl_$ = {};
vuehx__$Vue_Component_$Impl_$._new = function(x) {
	var this1 = x;
	return this1;
};
vuehx__$Vue_Component_$Impl_$.fromVuehxComponent = function(x) {
	var this1 = x.options;
	return this1;
};
var vuehx_IVueComponent = function() { };
Main.main();
})();
